//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::native_enum::Categories;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "category_status")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub created_date: DateTime,
  #[sea_orm(column_type = "Double")]
  pub vol24h: f64,
  #[sea_orm(column_type = "Double")]
  pub vol7d: f64,
  #[sea_orm(column_type = "Double")]
  pub vol30d: f64,
  #[sea_orm(column_type = "Double")]
  pub vol_all_time: f64,
  #[sea_orm(column_type = "Double")]
  pub first_place: f64,
  #[sea_orm(column_type = "Double")]
  pub last_place: f64,
  pub total_item: i32,
  pub totat_owner: i32,
  pub name: Categories,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
